### PR TITLE
Project finished

### PR DESCRIPTION
**Pull request by davidmrtz-dev**
- Project finished
- Added the video container
- description of video container

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Nicely done team :clap: 
I must say you folks did a really nice job on this project. Congratulations for the nice readme file and for using the GitHub flow :+1: 
You just missed a few things on this project:

- [x] The sidebar with the recommended videos must show the number of views for which video

- [x]  There are some errors in your HTML code. Check them using this HTML [validator](https://validator.w3.org/) . Ignore the warnings.

Please kindly make these changes and submit for code review again. Happy coding :muscle: 

[OPTIONAL]
It's best practice to use the `nav` tag for the navbar.

[OPTIONAL]
It's best practice to also use `main` tag for the main content of your page. In this project case, the video section.

[OPTIONAL]
And last but not least, it's also a good practice to use the `aside` tag for the aside sections of your page. All these 3 changes are related to best practices and semantic HTML(very important topic)

**Comment by davidmrtz-dev** [comment]
- Added the views of the recommended videos section.
- Fixed problems in the HTML validator

**Review by mosaaleb — APPROVED** [review]
### Well done @davitomix, @geraldgsh :clap:

You can merge into master :+1: 

Good luck with the next projects.

### Happy Coding :computer:

**Comment by geraldgsh** [comment]
Thank you @mosaaleb @Torres-ssf  🎉🎉🎉

**Pull request merged**
